#!/bin/bash

# USER CONFIG

########################################################################################

# Install to this directory
OPT=/opt/energenie_mqtt_client/

# Location for systemd files. Script assumes installing into a SystemV type environment.
SYSTEMD=/etc/systemd/system/

# Name of service file
SERVICE_FILE=docker-compose-energenie-mqtt.service

# Path to Docker Compose binary
DOCKER_COMPOSE_BIN=/usr/bin/docker-compose

# Path to docker-compose file
DOCKER_COMPOSE_YAML=docker-compose.yaml

########################################################################################

check_root() {
  if [[ $EUID -ne 0 ]]
    then echo "$0: Please run as root"
    exit 1
  fi
}

# Greeting message
greeting() {
echo "

Docker container and management for @gpbenton's MQTT client for Energenie RF.
(https://github.com/gpbenton/engMQTTClient)
  Note: Requires packages - docker-compose
                          - systemd
			  - mosquitto (or other MQTT broker)
"
}

# Service file creation
create_service_file() {
  SERVICE=${SYSTEMD}/${SERVICE_FILE}
  echo "Creating service file ..."
  cat << EOF > $SERVICE_FILE           
# DO NOT EDIT THIS FILE. IT IS CREATED BY the install SCRIPT FOR engMQTTClient DOCKER.
[Unit]
Description=Docker Compose Energenie MQTT Client service
Requires=docker.service
After=docker.service
[Service]
User=root
RemainAfterExit=yes
WorkingDirectory=${OPT}
ExecStart=${DOCKER_COMPOSE_BIN} -f ${OPT}/${DOCKER_COMPOSE_YAML} up --build energenie_mqtt_client 
ExecStop=${DOCKER_COMPOSE_BIN} -f ${OPT}/${DOCKER_COMPOSE_YAML} down
TimeoutStartSec=0
[Install]
WantedBy=multi-user.target
EOF
}

# Docker-compose config file
create_docker_compose_file() {
  echo "Creating docker-compose config ..."
  cat << EOF >$DOCKER_COMPOSE_YAML
# DO NOT EDIT THIS FILE. IT IS CREATED BY the install SCRIPT FOR engMQTTClient DOCKER.
version: '3'
services:
  energenie_mqtt_client:
    image: energenie_mqtt_client:1.0
    container_name: energenie_mqtt_client
    build: .
    privileged: true
    working_dir: $OPT
    network_mode: host
    entrypoint: /bin/sh -c 'LD_LIBRARY_PATH=/usr/local/lib ./engMQTTClient.exe 2>&1'
EOF
}

# Install (to /opt/energenie_mqqt_client by default)
install() {
  echo "Installing into $OPT ..."
  mkdir -p $OPT 
  cp -vf $SERVICE_FILE $SYSTEMD
  cp -vf $DOCKER_COMPOSE_YAML $OPT
  cp -vf Dockerfile $OPT 
  cp -vf run.sh $OPT 
  cp -vf stop.sh $OPT 
}

# Cleanup
cleanup() {
  echo "
  Use:-
    uudo systemctl [cmd] docker-compose-energenie-mqtt-client.service 
    -  where cmd = start | stop | restart  (as per systemd)
  "
}

# START OF INSTALL

{ 
check_root \
&& greeting \
&& create_docker_compose_file \
&& create_service_file \
&& install \
&& cleanup ; } && exit 0 || exit 1
